import * as Sentry from "@sentry/cloudflare";
// @ts-expect-error: generated by `npm run cf:build`, only present after that runs
import worker from "../.open-next/worker.js";

export default Sentry.withSentry(
  (env: CloudflareEnv) => ({
    dsn: "https://24b2d821973d608d346957ecd92e5710@o4511714712289280.ingest.us.sentry.io/4511714753511424",
  }),
  worker
);
